### PR TITLE
[WIP] Relay 0.8 support

### PR DESCRIPTION
**Pull request by edvinerikson**
The server is working fine.
However the client trashes the server markup due to `Relay.Renderer` renders null on the first render.
I have checked the discussion at https://github.com/facebook/relay/pull/921 but I am not entirely sure what the best approach would be here. 
`RootContainer -> checkCache(container, route) -> true -> render Relay.ReadyStateRenderer`
`RootContainer -> checkCache(container, route) -> false -> render Relay.Renderer`
?

### CODE REVIEW

**Comment by edvinerikson** [comment]
I tried the approach I suggested and it should work but it do not.
The server still works fine, however the client emits `RelayQueryWriter: Could not find a type name for record RmFjdGlvbjoy.` when it fetches from the server (works with server data). The problem is that Relay doesn't query the `__typename` field from the server.

**Comment by mattecapu** [comment]
It does work for me now

**Comment by edvinerikson** [comment]
@mattecapu That's awesome! Thank you for trying it! Did you try the StarWars example or did you have your own app?

**Comment by mattecapu** [comment]
I tried with the example, no errors both on client and server
My app uses isomorphic-relay-router on top of isomorphic-relay, and I don't think it's compatible yet. What do you think?

**Comment by edvinerikson** [comment]
Closing this out as of https://github.com/denvned/isomorphic-relay/commit/a800c706348c399217b4d696c3946e2b0bb25c02

@mattecapu No, it won't currently work as that lib relies on RootContainer which is removed in the latest release.

**Pull request closed without merging**
